// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // For now, return Android config for web (you should configure web properly)
      return android;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        // For now, return Android config for iOS (you should configure iOS properly)
        return android;
      case TargetPlatform.macOS:
        // For now, return Android config for macOS (you should configure macOS properly)
        return android;
      case TargetPlatform.windows:
        // For now, return Android config for Windows (you should configure Windows properly)
        return android;
      case TargetPlatform.linux:
        // For now, return Android config for Linux (you should configure Linux properly)
        return android;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzNbS8ptfgNGk8qySeGOwmC1_FWRmwSaE',
    appId: '1:464394607461:android:adfdd7d2290116cd98df8c',
    messagingSenderId: '464394607461',
    projectId: 'safety-app-487c6',
    storageBucket: 'safety-app-487c6.firebasestorage.app',
  );
}
